version: '2.1'

networks:
  monitor-net:
    driver: bridge

volumes:
    prometheus_data: {}
    grafana_data: {}

services:
  ##############################################################
  ######  Prometheus : Logiciel de monitoring           ########
  ##############################################################
  prometheus:
    image: prom/prometheus:v2.17.0
    container_name: ${PREFIX}_prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - /data/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    expose:
      - 9090
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"
  ##############################################################
  ######  alertmanager : Gère les alertes de Prometheus ########
  ##############################################################
  alertmanager:
    image: prom/alertmanager:v0.20.0
    container_name: ${PREFIX}_alertmanager
    volumes:
      - ./alertmanager:/etc/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    restart: unless-stopped
    expose:
      - 9093
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"
  ##############################################################
  ###  Node Exporter : Exporteur de métriques (CPU, RAM, ...) ##
  ##############################################################
  nodeexporter:
    image: prom/node-exporter:v0.18.1
    container_name: ${PREFIX}_nodeexporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /root:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    expose:
      - 9100
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"
  ##############################################################
  ###  BlackBox Exporter : Exporteur en boîte noire           ##
  ##############################################################
  blackbox_exporter:
    image: prom/blackbox-exporter
    dns: 8.8.8.8
    # restart: always
    ports:
      - "9115:9115"
    volumes:
      - ./blackbox:/etc/blackbox
    command: -config.file=/etc/blackbox/config.yml
  ##############################################################
  ######  Cadvisor : Collecteur de métrique de conteneur      ##
  ##############################################################
  cadvisor:
    image: gcr.io/google-containers/cadvisor:v0.34.0
    container_name: ${PREFIX}_cadvisor
    volumes:
      - /root:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      #- /cgroup:/cgroup:ro # ne fonctionne pas sur MacOS, que sous Linux
    restart: unless-stopped
    expose:
      - 8080
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"
  ##############################################################
  ######  Grafana : GUI pour le monitoring              ########
  ##############################################################
  grafana:
    image: grafana/grafana:6.7.1
    container_name: ${PREFIX}_grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/plugins:/var/lib/grafana/plugins
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_PATHS_PLUGINS=/var/lib/grafana/plugins
    restart: unless-stopped
    expose:
      - 3000
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"
  ##############################################################
  ######  pushgateway : Collecteur de données           ########
  ##############################################################
  pushgateway:
    image: prom/pushgateway:v1.2.0
    container_name: ${PREFIX}_pushgateway
    restart: unless-stopped
    expose:
      - 9091
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"
  ##############################################################
  #######  CADDY : Un proxy HTTP. Rédirige les requêtes ########
  ##############################################################
  caddy:
    image: stefanprodan/caddy
    container_name: ${PREFIX}_caddy
    ports:
      - "3000:3000"
      - "9090:9090"
      - "9093:9093"
      - "9091:9091"
    volumes:
      - ./caddy:/etc/caddy
    environment:
      - ADMIN_USER=${ADMIN_USER:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
    restart: unless-stopped
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"
  ##############################################################
  ######  logstash : Collecteur de données              ########
  ##############################################################
  logstash:
    image: logstash:7.4.2
    container_name: ${PREFIX}_logstash
    volumes:
      - ./logstash:/config-dir
    command: logstash -f /config-dir/logstash.conf

